# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install -e .
  - mme-server quickstart
script:
  - coverage run --source=mme_server setup.py test
services:
  - elasticsearch
before_script:
  # Delay for elasticsearch to start
  - sleep 10
before_install:
  - pip install coveralls
after_success:
  - coveralls
