# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - pip install -r requirements.txt
  - python main.py quickstart
script:
  - coverage run -m unittest
services:
  - elasticsearch
before_script:
  # Delay for elasticsearch to start
  - sleep 10
before_install:
  - pip install codecov
  - pip install coveralls
after_success:
  - codecov
  - coveralls
